-- meetings_adoption_daily
-- Review: 2018/03/21

SELECT
  date,
  SUM(CASE WHEN parameters.name = 'meet:average_meeting_minutes' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS average_meeting_minutes,
  SUM(CASE WHEN parameters.name = 'meet:average_meeting_minutes_with_11_to_15_calls' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS average_meeting_minutes_with_11_to_15_calls,
  SUM(CASE WHEN parameters.name = 'meet:average_meeting_minutes_with_16_to_25_calls' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS average_meeting_minutes_with_16_to_25_calls,
  SUM(CASE WHEN parameters.name = 'meet:average_meeting_minutes_with_26_to_50_calls' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS average_meeting_minutes_with_26_to_50_calls,
  SUM(CASE WHEN parameters.name = 'meet:average_meeting_minutes_with_2_calls' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS average_meeting_minutes_with_2_calls,
  SUM(CASE WHEN parameters.name = 'meet:average_meeting_minutes_with_3_to_5_calls' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS average_meeting_minutes_with_3_to_5_calls,
  SUM(CASE WHEN parameters.name = 'meet:average_meeting_minutes_with_6_to_10_calls' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS average_meeting_minutes_with_6_to_10_calls,
  SUM(CASE WHEN parameters.name = 'meet:lonely_meetings' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS lonely_meetings,
  SUM(CASE WHEN parameters.name = 'meet:max_concurrent_usage_chromebase' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS max_concurrent_usage_chromebase,
  SUM(CASE WHEN parameters.name = 'meet:max_concurrent_usage_chromebox' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS max_concurrent_usage_chromebox,
  SUM(CASE WHEN parameters.name = 'meet:num_1day_active_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_1day_active_users,
  SUM(CASE WHEN parameters.name = 'meet:num_30day_active_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_30day_active_users,
  SUM(CASE WHEN parameters.name = 'meet:num_7day_active_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_7day_active_users,
  SUM(CASE WHEN parameters.name = 'meet:num_calls' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_calls,
  SUM(CASE WHEN parameters.name = 'meet:num_calls_android' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_calls_android,
  SUM(CASE WHEN parameters.name = 'meet:num_calls_by_external_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_calls_by_external_users,
  SUM(CASE WHEN parameters.name = 'meet:num_calls_by_internal_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_calls_by_internal_users,
  SUM(CASE WHEN parameters.name = 'meet:num_calls_by_pstn_in_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_calls_by_pstn_in_users,
  SUM(CASE WHEN parameters.name = 'meet:num_calls_chromebase' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_calls_chromebase,
  SUM(CASE WHEN parameters.name = 'meet:num_calls_chromebox' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_calls_chromebox,
  SUM(CASE WHEN parameters.name = 'meet:num_calls_ios' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_calls_ios,
  SUM(CASE WHEN parameters.name = 'meet:num_calls_jamboard' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_calls_jamboard,
  SUM(CASE WHEN parameters.name = 'meet:num_calls_unknown_client' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_calls_unknown_client,
  SUM(CASE WHEN parameters.name = 'meet:num_calls_web' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_calls_web,
  SUM(CASE WHEN parameters.name = 'meet:num_meetings' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_meetings,
  SUM(CASE WHEN parameters.name = 'meet:num_meetings_android' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_meetings_android,
  SUM(CASE WHEN parameters.name = 'meet:num_meetings_chromebase' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_meetings_chromebase,
  SUM(CASE WHEN parameters.name = 'meet:num_meetings_chromebox' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_meetings_chromebox,
  SUM(CASE WHEN parameters.name = 'meet:num_meetings_ios' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_meetings_ios,
  SUM(CASE WHEN parameters.name = 'meet:num_meetings_jamboard' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_meetings_jamboard,
  SUM(CASE WHEN parameters.name = 'meet:num_meetings_unknown_client' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_meetings_unknown_client,
  SUM(CASE WHEN parameters.name = 'meet:num_meetings_web' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_meetings_web,
  SUM(CASE WHEN parameters.name = 'meet:num_meetings_with_11_to_15_calls' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_meetings_with_11_to_15_calls,
  SUM(CASE WHEN parameters.name = 'meet:num_meetings_with_16_to_25_calls' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_meetings_with_16_to_25_calls,
  SUM(CASE WHEN parameters.name = 'meet:num_meetings_with_26_to_50_calls' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_meetings_with_26_to_50_calls,
  SUM(CASE WHEN parameters.name = 'meet:num_meetings_with_2_calls' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_meetings_with_2_calls,
  SUM(CASE WHEN parameters.name = 'meet:num_meetings_with_3_to_5_calls' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_meetings_with_3_to_5_calls,
  SUM(CASE WHEN parameters.name = 'meet:num_meetings_with_6_to_10_calls' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_meetings_with_6_to_10_calls,
  SUM(CASE WHEN parameters.name = 'meet:num_meetings_with_external_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_meetings_with_external_users,
  SUM(CASE WHEN parameters.name = 'meet:num_meetings_with_pstn_in_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_meetings_with_pstn_in_users,
  SUM(CASE WHEN parameters.name = 'meet:total_call_minutes' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS total_call_minutes,
  SUM(CASE WHEN parameters.name = 'meet:total_call_minutes_android' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS total_call_minutes_android,
  SUM(CASE WHEN parameters.name = 'meet:total_call_minutes_by_external_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS total_call_minutes_by_external_users,
  SUM(CASE WHEN parameters.name = 'meet:total_call_minutes_by_internal_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS total_call_minutes_by_internal_users,
  SUM(CASE WHEN parameters.name = 'meet:total_call_minutes_by_pstn_in_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS total_call_minutes_by_pstn_in_users,
  SUM(CASE WHEN parameters.name = 'meet:total_call_minutes_chromebase' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS total_call_minutes_chromebase,
  SUM(CASE WHEN parameters.name = 'meet:total_call_minutes_chromebox' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS total_call_minutes_chromebox,
  SUM(CASE WHEN parameters.name = 'meet:total_call_minutes_ios' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS total_call_minutes_ios,
  SUM(CASE WHEN parameters.name = 'meet:total_call_minutes_jamboard' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS total_call_minutes_jamboard,
  SUM(CASE WHEN parameters.name = 'meet:total_call_minutes_unknown_client' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS total_call_minutes_unknown_client,
  SUM(CASE WHEN parameters.name = 'meet:total_call_minutes_web' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS total_call_minutes_web,
  SUM(CASE WHEN parameters.name = 'meet:total_meeting_minutes' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS total_meeting_minutes,
FROM
  [YOUR_PROJECT_ID:raw_data.customer_usage]
WHERE TRUE
  AND _PARTITIONTIME = YOUR_TIMESTAMP_PARAMETER
GROUP BY 1