-- customer_usage_date_summary_extended
-- Review: 07/08/2017
SELECT
  date,
  SUM(CASE WHEN parameters.name = 'accounts:gsuite_enterprise_used_licenses' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS gE_us_lic,
  SUM(CASE WHEN parameters.name = 'accounts:gsuite_enterprise_total_licenses' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS gE_t_lic,
  SUM(CASE WHEN parameters.name = 'accounts:gsuite_unlimited_used_licenses' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS gBS_us_lic,
  SUM(CASE WHEN parameters.name = 'accounts:gsuite_unlimited_total_licenses' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS gBS_to_lic,
  SUM(CASE WHEN parameters.name = 'accounts:gsuite_basic_used_licenses' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS gBA_us_lic,
  SUM(CASE WHEN parameters.name = 'accounts:gsuite_basic_total_licenses' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS gBA_to_lic,
  SUM(CASE WHEN parameters.name = 'accounts:num_disabled_accounts' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS disabled_accounts,
  SUM(CASE WHEN parameters.name = 'accounts:num_suspended_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS suspended_users,
  SUM(CASE WHEN parameters.name = 'accounts:num_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_users,
  SUM(CASE WHEN parameters.name = 'accounts:apps_total_licenses' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS apps_total_licenses,
  SUM(CASE WHEN parameters.name = 'accounts:apps_used_licenses' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS apps_used_licenses,
  SUM(CASE WHEN parameters.name = 'accounts:vault_total_licenses' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS vault_total_licenses,
  SUM(CASE WHEN parameters.name IN ('accounts:gsuite_enterprise_used_licenses', 'accounts:gsuite_basic_used_licenses', 'accounts:gsuite_unlimited_used_licenses') THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_used_licences,
  SUM(CASE WHEN parameters.name IN ('accounts:gsuite_enterprise_total_licenses', 'accounts:gsuite_unlimited_total_licenses', 'accounts:gsuite_basic_total_licenses') THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_total_licences,
  SUM(CASE WHEN parameters.name = 'accounts:num_1day_logins' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_1day_logins,
  SUM(CASE WHEN parameters.name = 'accounts:num_7day_logins' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_7day_logins,
  SUM(CASE WHEN parameters.name = 'accounts:num_30day_logins' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_30day_logins,
  SUM(CASE WHEN parameters.name = 'calendar:num_1day_active_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS calendar_n1dau,
  SUM(CASE WHEN parameters.name = 'calendar:num_7day_active_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS calendar_n7dau,
  SUM(CASE WHEN parameters.name = 'calendar:num_30day_active_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS calendar_n30dau,
  SUM(CASE WHEN parameters.name = 'cros:num_7day_active_devices' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_7day_active_devices,
  SUM(CASE WHEN parameters.name = 'cros:num_30day_active_devices' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_30day_active_devices,
  SUM(CASE WHEN parameters.name = 'classroom:num_1day_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS classroom_n1dau,
  SUM(CASE WHEN parameters.name = 'classroom:num_7day_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS classroom_n7dau,
  SUM(CASE WHEN parameters.name = 'classroom:num_30day_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS classroom_n30dau,
  SUM(CASE WHEN parameters.name = 'drive:num_1day_active_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS drive_n1dau,
  SUM(CASE WHEN parameters.name = 'drive:num_7day_active_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS drive_n7dau,
  SUM(CASE WHEN parameters.name = 'drive:num_30day_active_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS drive_n30dau,
  SUM(CASE WHEN parameters.name = 'drive:num_30day_google_documents_active_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS docs_n30dau,
  SUM(CASE WHEN parameters.name = 'drive:num_30day_google_spreadsheets_active_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS sheets_n30dau,
  SUM(CASE WHEN parameters.name = 'drive:num_30day_google_presentations_active_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS slides_n30dau,
  SUM(CASE WHEN parameters.name = 'drive:num_30day_google_forms_active_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS forms_n30dau,
  SUM(CASE WHEN parameters.name = 'drive:num_30day_google_drawings_active_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS draws_n30dau,
  SUM(CASE WHEN parameters.name = 'drive:num_30day_other_types_active_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS drive_other_n30dau,
  SUM(CASE WHEN parameters.name = 'drive:num_creators' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_creators,
  SUM(CASE WHEN parameters.name = 'drive:num_collaborators' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_collaborators,
  SUM(CASE WHEN parameters.name = 'drive:num_consumers' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_consumers,
  SUM(CASE WHEN parameters.name = 'drive:num_sharers' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_sharers,
  SUM(CASE WHEN parameters.name = 'gmail:num_1day_active_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS gmail_n1dau,
  SUM(CASE WHEN parameters.name = 'gmail:num_7day_active_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS gmail_n7dau,
  SUM(CASE WHEN parameters.name = 'gmail:num_30day_active_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS gmail_n30dau,
  SUM(CASE WHEN parameters.name = 'gplus:num_1day_active_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS gplus_n1dau,
  SUM(CASE WHEN parameters.name = 'gplus:num_7day_active_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS gplus_n7dau,
  SUM(CASE WHEN parameters.name = 'gplus:num_30day_active_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS gplus_n30dau,
  SUM(CASE WHEN parameters.name = 'device_management:num_30day_google_sync_managed_devices' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_30day_google_sync_managed_devices,
  SUM(CASE WHEN parameters.name = 'device_management:num_30day_android_managed_devices' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_30day_android_managed_devices,
  SUM(CASE WHEN parameters.name = 'device_management:num_30day_ios_managed_devices' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_30day_ios_managed_devices,
  SUM(CASE WHEN parameters.name = 'device_management:num_30day_total_managed_devices' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_30day_total_managed_devices,
  SUM(CASE WHEN parameters.name = 'device_management:num_30day_google_sync_managed_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_30day_google_sync_managed_users,
  SUM(CASE WHEN parameters.name = 'device_management:num_30day_android_managed_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_30day_android_managed_users,
  SUM(CASE WHEN parameters.name = 'device_management:num_30day_ios_managed_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_30day_ios_managed_users,
  SUM(CASE WHEN parameters.name = 'device_management:num_30day_total_managed_users' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_30day_total_managed_users,
  SUM(CASE WHEN parameters.name = 'sites:num_sites' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_sites,
  SUM(CASE WHEN parameters.name = 'sites:num_sites_created' THEN (IFNULL(parameters.intValue,NULL)) ELSE 0 END) AS num_sites_created,
FROM
  [YOUR_PROJECT_ID:raw_data.customer_usage]
WHERE TRUE
  AND _PARTITIONTIME = YOUR_TIMESTAMP_PARAMETER
GROUP BY 1